version: "3"
services:
  mongo:
    container_name: mongo-link-api
    image: mongo:3
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
volumes:
  mongodbdata:
